name: Admintools3
version: @version@
main: dev.wwst.admintools3.AdminTools3
authors: [Weiiswurst]
description: AdminTools v3
website: ks1.xyz
api-version: "1.13"
softdepend:
  - ProtocolLib
  - Vault

commands:
  admingui:
    description: Opens the AdminTools3 GUI
    usage: /a [<module> [player] [world]]
    aliases:
      - a
      - admintools


permissions:
  admintools3.use:
    description: Needed to use the plugin
  admintools3.bypass.cooldown:
    description: Bypass Module cooldowns. admintools3.bypass.cooldown.<modulename> to bypass individual cooldowns.
  admintools3.bypass.freeze:
    description: You cannot be freezed anymore.
  admintools3.bypass.mute:
    description: You cannot be muted anymore.
  admintools3.bypass.vanish:
    description: You can see players that are in vanish mode.